---
- hosts: localhost
  connection: local
  gather_facts: false
  # k8s_kubeconfig_src is required
  tasks:
    - name: read service configuration file
      include_vars:
        file:  "{{ cache_service_config_file | default('configs/default.yml') }}"
    - name: prepare api access config
      template:
        src: kubeconfig.j2
        dest: kubeconfig.tmp
        mode: '0400'
    - name: define cache service resource
      k8s:
        state: "{{ cache_service_state | default(omit) }}"
        definition: "{{ lookup('template', 'k8s-cache-service-def.yaml.j2') | from_yaml }}"
        kubeconfig: "{{ k8s_cluster_config | default('kubeconfig.tmp') }}"
